# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift News App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift News App
  pod 'DropDown', '2.3.4'

  target 'Swift News AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift News AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
